const UUID={service:'6e400001-b5a3-f393-e0a9-e50e24dcca9e',rx:'6e400002-b5a3-f393-e0a9-e50e24dcca9e',tx:'6e400003-b5a3-f393-e0a9-e50e24dcca9e'};
const VELOCITY_MIN=0,VELOCITY_MAX=1200;
const velocityLabels=[['PPP mínimo',2],['PPP máximo',41],['PP máximo',54],['P máximo',67],['MP máximo',79],['MF máximo',92],['F máximo',106],['FF máximo',119],['FFF máximo',127]];
const noteNames=['Do','Do♯','Re','Re♯','Mi','Fa','Fa♯','Sol','Sol♯','La','La♯','Si'];
const state={device:null,server:null,rx:null,tx:null,connected:false,busy:false,simulator:false,module:0,queue:Promise.resolve(),pendingReads:[],velocity:{white:Array(9).fill(0),black:Array(9).fill(0)},offsets:Array(12).fill(0),receivedKeys:Array(12).fill(false)};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function hex(bytes){return [...bytes].map(v=>v.toString(16).padStart(2,'0').toUpperCase()).join(' ')}
function log(message,type='INFO'){const line=`${new Date().toLocaleTimeString()} [${type}] ${message}`; $('#log').textContent+=line+'\n'; $('#log').scrollTop=$('#log').scrollHeight}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function setStatus(label,kind='offline'){const b=$('#statusBadge');b.textContent=label;b.className=`badge ${kind}`}
function setEnabled(){const ready=state.connected||state.simulator;['#readModuleBtn','#readVelocityBtn','#writeVelocityBtn','#readOffsetsBtn','#writeOffsetsBtn'].forEach(s=>$(s).disabled=!ready);$('#disconnectBtn').disabled=!state.connected;$('#connectBtn').disabled=state.connected||state.simulator}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
function int16Bytes(value){const n=Number(value);if(!Number.isInteger(n)||n<-32768||n>32767)throw new Error('Valor fuera del rango int16');const u=n&0xffff;return [u>>8,u&255]}
function uint16Bytes(value){const n=Number(value);if(!Number.isInteger(n)||n<0||n>65535)throw new Error('Valor fuera del rango 0–65535');return [n>>8,n&255]}
function cmd(...values){if(values.length!==6)throw new Error('Los comandos deben tener 6 bytes');return new Uint8Array(values.map(v=>v&255))}
async function connect(){try{if(!navigator.bluetooth)throw new Error('Web Bluetooth no está disponible en este navegador. Usa Chrome en Android y abre la web por HTTPS.');setStatus('Buscando…','busy');log('Abriendo selector Bluetooth sin filtro de anuncio BLE…','BLE');state.device=await navigator.bluetooth.requestDevice({acceptAllDevices:true,optionalServices:[UUID.service]});state.device.addEventListener('gattserverdisconnected',onDisconnected);setStatus('Conectando…','busy');state.server=await state.device.gatt.connect();log(`Conectado a GATT. Buscando servicio ${UUID.service}…`,'BLE');const service=await state.server.getPrimaryService(UUID.service);state.rx=await service.getCharacteristic(UUID.rx);state.tx=await service.getCharacteristic(UUID.tx);await state.tx.startNotifications();state.tx.addEventListener('characteristicvaluechanged',onNotification);state.connected=true;$('#deviceName').textContent=state.device.name||'PocketPiano';$('#deviceInfo').textContent=`${state.device.name||'PocketPiano'} conectado`;setStatus('Conectado','online');setEnabled();log(`Conectado a ${state.device.name||'dispositivo BLE'}`,'OK');toast('PocketPiano conectado')}catch(e){if(state.device?.gatt?.connected)state.device.gatt.disconnect();state.connected=false;state.server=state.rx=state.tx=null;setStatus('Desconectado','offline');log(`${e.name||'Error'}: ${e.message}`,'ERROR');toast(e.message);setEnabled()}}
function disconnect(){if(state.device?.gatt?.connected)state.device.gatt.disconnect();else onDisconnected()}
function onDisconnected(){state.connected=false;state.server=state.rx=state.tx=null;setStatus('Desconectado','offline');$('#deviceInfo').textContent='Ningún dispositivo conectado';setEnabled();log('Dispositivo desconectado','WARN')}
async function rawWrite(packet){log(`TX  ${hex(packet)}`,'BLE');if(state.simulator){await sleep(35);simulateResponse(packet);return}if(!state.connected||!state.rx)throw new Error('No hay conexión BLE');if(typeof state.rx.writeValueWithoutResponse==='function')await state.rx.writeValueWithoutResponse(packet);else if(typeof state.rx.writeValueWithResponse==='function')await state.rx.writeValueWithResponse(packet);else await state.rx.writeValue(packet)}
function send(packet,delay=80){state.queue=state.queue.then(()=>rawWrite(packet)).then(()=>sleep(delay));return state.queue.catch(e=>{log(e.message,'ERROR');throw e})}
function onNotification(event){const data=new Uint8Array(event.target.value.buffer,event.target.value.byteOffset,event.target.value.byteLength);handleResponse(data)}
function handleResponse(data){log(`RX  ${hex(data)}`,'BLE');if(data.length>=5){const opcode=data[0],group=data[1],index=data[2],unsigned=(data[3]<<8)|data[4],signed=unsigned&0x8000?unsigned-0x10000:unsigned;if((opcode===0x26||opcode===0x25)&&index<9){const target=group===1?'black':'white';state.velocity[target][index]=Math.max(VELOCITY_MIN,Math.min(VELOCITY_MAX,unsigned));renderVelocity()}if((opcode===0x21||opcode===0x20)&&index>=1&&index<=12){state.offsets[index-1]=signed;state.receivedKeys[index-1]=true;renderOffsets();renderKeyReadings()}}const text=new TextDecoder().decode(data).replace(/\0/g,'').trim();if(text&&/[\x20-\x7E]{3,}/.test(text))log(`Texto: ${text}`,'RX')}
function simulateResponse(packet){const [op,a,b]=packet;if(op===0x26)handleResponse(cmd(op,a,b,0,(20+b*12+a*3)&255,0));else if(op===0x21){const v=(b-6)*2,[hi,lo]=int16Bytes(v);handleResponse(cmd(op,a,b,hi,lo,0))}else if(op===0x10){$('#serialNumber').textContent=`SIM-${a}-240716`;log('Serie simulada recibida','SIM')}else if(op===0x0E){$('#firmwareVersion').textContent='1.0-SIM';log('Firmware simulado recibido','SIM')}}
function renderKeyReadings(){const c=$('#keyReadings');if(!c)return;const indices=state.module===0?[9,10,11]:noteNames.map((_,i)=>i);c.classList.remove('hidden');c.classList.toggle('module-zero',state.module===0);c.innerHTML=indices.map(i=>`<div class="key-reading ${noteNames[i].includes('♯')?'black-note':'white-note'}" data-key="${i+1}"><strong>${i+1}</strong><span>${noteNames[i]}</span><output>${state.receivedKeys[i]?state.offsets[i]:'—'}</output></div>`).join('')}
function updateModuleImage(){const image=$('#moduleImage');if(!image)return;const isModuleZero=state.module===0;image.src=isModuleZero?'assets/module-0.svg?v=20260716-20':'assets/module-octave.svg?v=20260716-20';image.alt=isModuleZero?'Módulo 0 PocketPiano':'Octava de teclas de piano desde Do hasta Si';image.width=600;image.height=600;renderKeyReadings()}
async function selectModule(i){state.module=i;state.offsets=Array(12).fill(0);state.receivedKeys=Array(12).fill(false);renderModules();updateModuleImage();renderOffsets();$('#activeModule').textContent=i;$('#serialNumber').textContent='—';$('#firmwareVersion').textContent='—';if(state.connected||state.simulator){await send(cmd(0x23,1<<i,0,0,0,0))}}
async function readModule(){await send(cmd(0x10,state.module,0,0,0,0));await send(cmd(0x0E,state.module,0,0,0,0));if(!state.simulator)toast('Solicitud enviada; consulta la consola para validar la respuesta del firmware')}
async function readVelocity(){try{setStatus('Leyendo…','busy');for(let group=0;group<2;group++)for(let i=0;i<9;i++)await send(cmd(0x26,group,i,0,0,0));setStatus(state.simulator?'Simulación':'Conectado','online');toast('Lectura de velocity terminada')}catch(e){setStatus('Error','offline');toast(e.message)}}
async function writeVelocity(){try{readVelocityInputs();setStatus('Guardando…','busy');for(const [group,key] of [[0,'white'],[1,'black']])for(let i=0;i<9;i++){const [hi,lo]=uint16Bytes(state.velocity[key][i]);await send(cmd(0x25,group,i,hi,lo,0))}setStatus(state.simulator?'Simulación':'Conectado','online');toast('Velocity guardada')}catch(e){setStatus('Error','offline');toast(e.message)}}
async function readOffsets(){try{state.receivedKeys=Array(12).fill(false);renderKeyReadings();setStatus('Leyendo…','busy');const keys=state.module===0?[10,11,12]:Array.from({length:12},(_,i)=>i+1);for(const key of keys)await send(cmd(0x21,state.module,key,0,0,0));setStatus(state.simulator?'Simulación':'Conectado','online');toast(state.module===0?'Tiempos de las teclas 10–12 recibidos':'Tiempos recibidos')}catch(e){setStatus(state.simulator?'Simulación':state.connected?'Conectado':'Desconectado',state.simulator||state.connected?'online':'offline');toast(e.message)}}
async function writeOffsets(){try{readOffsetInputs();setStatus('Guardando…','busy');for(let key=1;key<=12;key++){const [hi,lo]=int16Bytes(state.offsets[key-1]);await send(cmd(0x20,state.module,key,hi,lo,0))}setStatus(state.simulator?'Simulación':'Conectado','online');toast('Offsets guardados')}catch(e){setStatus('Error','offline');toast(e.message)}}
function renderModules(){const c=$('#moduleSelector');c.innerHTML='';for(let i=0;i<=7;i++){const b=document.createElement('button');b.textContent=i;b.className='module-button'+(i===state.module?' active':'');b.onclick=()=>selectModule(i);c.append(b)}}
function bindVelocityControls(){$$('[data-velocity-slider]').forEach(slider=>{slider.oninput=()=>{const key=slider.dataset.velocitySlider,index=Number(slider.dataset.index),value=Number(slider.value),number=$(`[data-velocity="${key}"][data-index="${index}"]`);state.velocity[key][index]=value;if(number)number.value=value}});$$('[data-velocity]').forEach(number=>{number.oninput=()=>{const key=number.dataset.velocity,index=Number(number.dataset.index),value=Math.max(VELOCITY_MIN,Math.min(VELOCITY_MAX,Number(number.value)||0)),slider=$(`[data-velocity-slider="${key}"][data-index="${index}"]`);state.velocity[key][index]=value;number.value=value;if(slider)slider.value=value}})}
function renderVelocity(){for(const [id,key] of [['whiteVelocity','white'],['blackVelocity','black']]){$(`#${id}`).innerHTML=velocityLabels.map(([label,midi],i)=>`<div class="number-field ${key==='white'?'with-slider':''}">${key==='white'?`<div class="velocity-slider-wrap"><input class="velocity-slider" data-velocity-slider="${key}" data-index="${i}" type="range" min="${VELOCITY_MIN}" max="${VELOCITY_MAX}" step="1" value="${state.velocity[key][i]}" aria-label="${label}"></div>`:''}<input data-velocity="${key}" data-index="${i}" type="number" min="${VELOCITY_MIN}" max="${VELOCITY_MAX}" value="${state.velocity[key][i]}"><label>${label}<small>MIDI ${midi}</small></label></div>`).join('')}bindVelocityControls()}
function renderOffsets(){$('#offsetGrid').innerHTML=state.offsets.map((v,i)=>`<div class="offset-item"><label>Tecla ${i+1}<output id="time-${i}">${state.receivedKeys[i]?v:'—'}</output></label><input data-offset="${i}" type="number" min="-32768" max="32767" value="${v}"></div>`).join('')}
function readVelocityInputs(){$$('[data-velocity]').forEach(input=>{const n=Number(input.value);if(!Number.isInteger(n)||n<VELOCITY_MIN||n>VELOCITY_MAX)throw new Error(`Velocity inválida en ${input.dataset.velocity}, nivel ${Number(input.dataset.index)+1}. Rango permitido: ${VELOCITY_MIN}–${VELOCITY_MAX}`);state.velocity[input.dataset.velocity][Number(input.dataset.index)]=n})}
function readOffsetInputs(){$$('[data-offset]').forEach(input=>{const n=Number(input.value);if(!Number.isInteger(n)||n<-32768||n>32767)throw new Error(`Offset inválido en tecla ${Number(input.dataset.offset)+1}`);state.offsets[Number(input.dataset.offset)]=n})}
$$('.tab').forEach(btn=>btn.onclick=()=>{$$('.tab').forEach(x=>x.classList.toggle('active',x===btn));$$('.panel').forEach(p=>p.classList.toggle('active',p.id===btn.dataset.tab))});
$('#connectBtn').onclick=connect;$('#disconnectBtn').onclick=disconnect;$('#readModuleBtn').onclick=readModule;$('#readVelocityBtn').onclick=readVelocity;$('#writeVelocityBtn').onclick=writeVelocity;$('#readOffsetsBtn').onclick=readOffsets;$('#writeOffsetsBtn').onclick=writeOffsets;$('#clearLogBtn').onclick=()=>$('#log').textContent='';
$('#simulatorToggle').onchange=e=>{state.simulator=e.target.checked;if(state.simulator&&state.connected)disconnect();setStatus(state.simulator?'Simulación':'Desconectado',state.simulator?'online':'offline');$('#deviceInfo').textContent=state.simulator?'Hardware simulado localmente':'Ningún dispositivo seleccionado';$('#deviceName').textContent=state.simulator?'PocketPiano Simulator':'—';setEnabled();log(state.simulator?'Modo simulación activado':'Modo simulación desactivado','SIM')};
if(!window.isSecureContext){const w=$('#compatWarning');w.textContent='Web Bluetooth solo funciona en un contexto seguro (HTTPS o localhost).';w.classList.remove('hidden')}
if(!navigator.bluetooth){const w=$('#compatWarning');w.textContent='Este navegador no expone Web Bluetooth. Abre esta página con Google Chrome en Android.';w.classList.remove('hidden')}
renderModules();updateModuleImage();renderVelocity();renderOffsets();setEnabled();log('Aplicación iniciada. Selector BLE compatible con dispositivos que no anuncian el UUID NUS.');